### ISSUE TITLE
SD WebUI

### ISSUE THREAD

**Issue by cbresciano** [liriliri/vivy-docs#6]
In what SD WebUI concerns, I started the file webui.bat. It worked OK downloading many files and intalling them until stopped with a message in the console. I started it a second time and stopped in the same point with this messages:

venv "F:\VIVY-0.13.0-win\resources\app.asar.unpacked\webui\stable-diffusion-webui\venv\Scripts\Python.exe"
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: <none>
Commit hash: <none>
Couldn't determine assets's hash: 6f7db241d2f8ba7457bac5ca9753331f0c266917, attempting autofix...
Fetching all contents for assets
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "F:\VIVY-0.13.0-win\resources\app.asar.unpacked\webui\stable-diffusion-webui\launch.py", line 51, in <module>
    main()
  File "F:\VIVY-0.13.0-win\resources\app.asar.unpacked\webui\stable-diffusion-webui\launch.py", line 39, in main
    prepare_environment()
  File "F:\VIVY-0.13.0-win\resources\app.asar.unpacked\webui\stable-diffusion-webui\modules\launch_utils.py", line 414, in prepare_environment
    git_clone(assets_repo, repo_dir('stable-diffusion-webui-assets'), "assets", assets_commit_hash)
  File "F:\VIVY-0.13.0-win\resources\app.asar.unpacked\webui\stable-diffusion-webui\modules\launch_utils.py", line 177, in git_clone
    current_hash = run_git(dir, name, 'rev-parse HEAD', None, f"Couldn't determine {name}'s hash: {commithash}", live=False).strip()
  File "F:\VIVY-0.13.0-win\resources\app.asar.unpacked\webui\stable-diffusion-webui\modules\launch_utils.py", line 165, in run_git
    git_fix_workspace(dir, name)
  File "F:\VIVY-0.13.0-win\resources\app.asar.unpacked\webui\stable-diffusion-webui\modules\launch_utils.py", line 152, in git_fix_workspace
    run(f'"{git}" -C "{dir}" fetch --refetch --no-auto-gc', f"Fetching all contents for {name}", f"Couldn't fetch {name}", live=True)
  File "F:\VIVY-0.13.0-win\resources\app.asar.unpacked\webui\stable-diffusion-webui\modules\launch_utils.py", line 115, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't fetch assets.
Command: "git" -C "F:\VIVY-0.13.0-win\resources\app.asar.unpacked\webui\stable-diffusion-webui\repositories\stable-diffusion-webui-assets" fetch --refetch --no-auto-gc
Error code: 128

**Comment by surunzi** [comment]
You cannot directly run SD-WebUI. You need to enable the Stable Diffusion web UI in the settings, then restart the application. After that, you can open it through the menu by going to Tools -> Stable Diffusion web UI, or you can directly access it at 127.0.0.1:7860.
